kind: Service
apiVersion: v1
metadata:
  name: demo-apps
spec:
  type: NodePort
  selector:
    app: demo-apps
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30002

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-apps-deployment
  labels:
    app: demo-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-apps
  template:
    metadata:
      labels:
        app: demo-apps
    spec:
      containers:
      - name: demo-apps
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
